// <auto-generated />
using Computador;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Computador.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190529144912_NovoModel")]
    partial class NovoModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Computador.Models.Maquina", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Chave");

                    b.Property<string>("Marca");

                    b.Property<string>("Setor");

                    b.HasKey("Id");

                    b.ToTable("Maquina");
                });
#pragma warning restore 612, 618
        }
    }
}
